### ISSUE TITLE
update_deleted_packages fails on dirname

### ISSUE THREAD

**Issue by mingp** [bazel-contrib/rules_bazel_integration_test#189] opened 2023-09-01 17:47 UTC
I'm trying to set up `rules_bazel_integration` test, following the instructions in the project README. When I try to run `update_deleted_packages`, it fails with this error output:

```
$ bazel run @rules_bazel_integration_test//tools:update_deleted_packages
INFO: Analyzed target @rules_bazel_integration_test//tools:update_deleted_packages (131 packages loaded, 544 targets configured).
INFO: Found 1 target...
Target @rules_bazel_integration_test//tools:update_deleted_packages up-to-date:
  bazel-bin/external/rules_bazel_integration_test/tools/update_deleted_packages
INFO: Elapsed time: 28.774s, Critical Path: 0.10s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
dirname: missing operand
Try 'dirname --help' for more information.
```

From what I can tell, one way to hit this error is to attempt to pass a blank/whitespace argument to `dirname`. If I were to guess, somewhere in one of the helpers, a path is constructed to pass to `dirname`, but accidentally ends up blank/empty.

Any advice on how to debug this further would be greatly appreciated. Thank you in advance.

**Comment by cgrindel** [comment] 2023-09-05 20:02
@mingp If you can create a repro that demonstrates the error, that would be great. In terms of debugging, you can clone this repo locally, add `set -x` to `tools/update_deleted_packages.sh` in your local clone, and update your repo to use the local clone. This will dump out a bunch of output to stderr showing all of the bash execution. Hopefully, it will be obvious what the culprit is.

**Comment by mingp** [comment] 2023-09-06 20:01
Thanks for the information, @cgrindel.

At present, my only repro involves a large proprietary workspace. I'm not sure if I can create a reduced repro that I can share.

I will try with additional debugging and see what happens.

**Comment by rickeylev** [comment] 2024-01-06 23:55
We just switched over to rules_bazel_integration_test in rules Python and also see this error. A relatively easy repro would be to clone rules_python and run `bazel run @rules_bazel_integration_test//tools:update_deleted_packages`. It should spew a bunch of "dirname: missing operand" errors

**Comment by cgrindel** [comment] 2024-01-07 16:01
Sorry. This issue fell off of my radar. I will take a look in the coming week.

**Comment by cgrindel** [comment] 2024-01-07 17:04
@rickeylev I tried to reproduce the error per your instructions. I did not experience an error running the command using the `main` branch. Is there another branch that I should try?

**Comment by cgrindel** [comment] 2024-01-07 17:42
I have tried a few things to reproduce and I am still not having any luck. One thing that I did notice is that we were not respecting `.bazelignore` entries when looking for Bazel packages. #266 fixes that. 

@mingp @rickeylev Which OS were you running when you saw this issue?

**Comment by cgrindel** [comment] 2024-01-08 20:32
@rickeylev @mingp We merged #266 and created [release 0.21.0](https://github.com/bazel-contrib/rules_bazel_integration_test/releases/tag/v0.21.0). Can you check if this issue still exists?

**Comment by rickeylev** [comment] 2024-01-09 07:51
Nope, same dirname: missing operand error with release 0.21

* Linux, debian rodete 
* Bash 5.2.15
* Bazel 7
* bzlmod enabled

I'm running in the client root (i.e. same dir as .bazelrc)

I can't think of anything else special.

**Comment by rickeylev** [comment] 2024-01-09 08:13
I narrowed it down when `find ... | xargs dirname` runs and the find doesn't find anything. This results in zero input to xargs, but xargs runs the command at least once anyways (sometimes). manpage: https://man7.org/linux/man-pages/man1/xargs.1.html#:~:text=example.%0A%0A%20%20%20%20%20%20%20%2Dr%2C%20%2D%2D-,no%2Drun%2Dif%2Dempty,-If%20the%20standard

Adding `-r` to the xargs call makes it work. Note, however, the manage says -r is a gnu extension; I think this means it won't work on a Mac.

The "sometimes" is because some of the SO comments below indicate BSD xargs _doesn't_ run the command if there isn't any input; I think mac is more BSD-like (which might explain why -r isn't a think for it)

I found a couple SO posts talking about this:
 * https://stackoverflow.com/questions/34440312/preventing-posix-xargs-from-attempting-to-run-an-empty-command
 * https://stackoverflow.com/questions/8296710/how-to-ignore-xargs-commands-if-stdin-input-is-empty

**Comment by rickeylev** [comment] 2024-01-09 08:20
Reading the SO posts, it sounds like `-I {}` is the trick to make it cross-platform and not run if there's no matches. e.g.

```
find ... | xargs -I {} dirname {}`
```

This works on my machine. I don't have a mac handy, so I can't try it there to verify.

**Comment by cgrindel** [comment] 2024-01-09 12:54
Great. I will test on my Mac.

**Closed** 2024-01-16 13:30 UTC
Labels: bug

**Comment by mingp** [comment] 2024-01-18 06:41
Thank you for solving this issue.

I don't have my original repro available to confirm any more, but I anticipate doing more work with this package - particularly, with a Mac - in the eventual future. If anything comes up, I can follow up again.
